# Changes here will be overwritten by Copier
_commit: 19e9a20
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
include_wkhtmltopdf: false
odoo_version: 13.0
rebel_module_groups: []
repo_description: Certification Modules based on BlockChain
repo_name: cert_blockchain
repo_slug: cert_blockchain
travis_apt_packages: []
travis_apt_sources: []
