from . import res_company
from . import res_config_settings
from . import survey_survey
from . import survey_user_input
from . import event_event
from . import gamification_badge
from . import sale_order
from . import res_partner
from . import res_users
from . import event_registration
